# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-02 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AWWARDS', '0002_auto_20190802_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
