# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-02 12:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AWWARDS', '0003_auto_20190802_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
